export const CURSOSCFIELDS = [
	{
		nombre: "CategoriaID",
		inputLabel: "Categoria Id",
		type: "text",
		id: 1,
		nroOrden: 4,
	},
	{
		nombre: "PDF",
		inputLabel: "Plan de estudios PDF",
		type: "text",
		id: 2,
		nroOrden: 5,
	},
	{
		nombre: "categoria",
		inputLabel: "Nombre de categoria",
		isRequired: true,
		type: "text",
		id: 3,
		nroOrden: 3,
	},
	{
		nombre: "detalles",
		inputLabel: "Tabla de datos",
		children: [
			{ nombre: "clasesSemanales", type: "text", id: 4 },
			{ nombre: "descripcion", type: "text", id: 5 },
			{ nombre: "duracionClase", type: "text", id: 6 },
			{ nombre: "duracionTotal", type: "text", id: 7 },
			{ nombre: "modalidad", type: "text", id: 8 },
			{ nombre: "requisitos", type: "text", id: 9 },
		],
	},
	{
		nombre: "href",
		inputLabel: "Path",
		isRequired: true,
		type: "text",
		id: 10,
		nroOrden: 2,
	},
	{
		nombre: "nombre",
		inputLabel: "Nombre del Curso",
		isRequired: true,
		type: "text",
		id: 11,
		nroOrden: 1,
	},
	{
		nombre: "planDeEstudioContent",
		inputLabel: "Plan de estudios descripcion",
		type: "text",
		id: 12,
		children: [],
	},
]
