export const ADMINPERFIL = [
  {
    nombre: 'Nombre',
    inputLabel: 'Nombre Completo',
    isRequired: true,
    type: 'text',
    id: 1,
    nroOrden: 1,
    width: '80%',
  },
  {
    nombre: 'Email',
    inputLabel: 'Email',
    isRequired: true,
    type: 'text',
    id: 2,
    nroOrden: 2,
    width: '80%',
  },
  {
    nombre: 'Contrasena',
    inputLabel: 'Antigua Contraseña',
    isRequired: true,
    type: 'text',
    id: 2,
    nroOrden: 2,
    width: '80%',
  },
  {
    nombre: 'Contrasena',
    inputLabel: 'Nueva Contraseña',
    isRequired: true,
    type: 'text',
    id: 3,
    nroOrden: 3,
    width: '80%',
  },
  {
    nombre: 'RepetirContrasena',
    inputLabel: 'Repetir Contraseña',
    isRequired: true,
    type: 'text',
    id: 4,
    nroOrden: 4,
    width: '80%',
  },
];
