export const USUARIOSFIELDS = [
    {
      nombre: 'name',
      inputLabel: 'Nombre',
      isRequired: true,
      type: 'text',
      id: 1,
      nroOrden: 1,
      width: '45%',
    },
    {
      nombre: 'lastname',
      inputLabel: 'Apellido',
      isRequired: true,
      type: 'text',
      id: 2,
      nroOrden: 2,
      width: '45%',
    },
    {
      nombre: 'email',
      inputLabel: 'Email',
      isRequired: true,
      type: 'text',
      id: 3,
      nroOrden: 3,
      width: '45%',
    },
    {
      nombre: 'dni',
      inputLabel: 'DNI',
      isRequired: true,
      type: 'number',
      id: 4,
      nroOrden: 4,
      width: '45%',
    },
    {
        nombre: 'phonenumber',
        inputLabel: 'Telefono',
        isRequired: true,
        type: 'number',
        id: 5,
        nroOrden: 5,
        width: '45%',
    },
    {
      nombre: 'personalInformation',
      inputLabel: 'Informacion Profesional',
      isRequired: true,
      type: 'text',
      id: 6,
      nroOrden: 6,
      width: '45%',
    },

  ];
  
  export const USUARIOSROWS = [
    {
      nombre: 'Id',
    },
    {
        nombre: 'name',
        inputLabel: 'Nombre',
        isRequired: true,
        type: 'text',
        id: 1,
        nroOrden: 1,
        width: '45%',
      },
      {
        nombre: 'lastname',
        inputLabel: 'Apellido',
        isRequired: true,
        type: 'text',
        id: 2,
        nroOrden: 2,
        width: '45%',
      },
      {
        nombre: 'email',
        inputLabel: 'Email',
        isRequired: true,
        type: 'text',
        id: 3,
        nroOrden: 3,
        width: '45%',
      },
      {
        nombre: 'dni',
        inputLabel: 'DNI',
        isRequired: true,
        type: 'number',
        id: 4,
        nroOrden: 4,
        width: '45%',
      },
    {
      nombre: 'Editar/Ocultar',
      inputLabel: 'Programa de estudio',
      helpText: 'Este es un ejemplo autogenerado',
      type: 'text',
      id: 13,
      children: [],
      nroOrden: 15,
      width: '45%',
    },
  ];
  